In [3]:
import pandas as pd
import numpy as np
from IPython.display import Image

In [4]:
# always_recycle_art/composites/ # 3728 composites
# always_recycle_art/cropped_inputs/ # 57 images, 3 versions each
# existential_day_100/composites/labels.csv

labels_df = pd.read_csv("existential_day_100/composites/labels.csv")
labels_df.head()

,Unnamed: 0,image,label,percentage
0,0,existential_day_100/composites/composite_215.jpg,"sea anemone, anemone",15.625580
1,1,existential_day_100/composites/composite_201.jpg,safety pin,44.522686
2,2,existential_day_100/composites/composite_26.jpg,"handkerchief, hankie, hanky, hankey",26.242722
3,3,existential_day_100/composites/composite_32.jpg,"spider web, spider's web",21.648129
4,4,existential_day_100/composites/composite_188.jpg,jigsaw puzzle,28.188601

In [43]:
labels_df = pd.read_csv("existential_day_100/composites/labels.csv")
labels_df["label"] = [x.split(",")[0] for x in labels_df["label"]]

for l in sorted(labels_df.label.unique()):
    print(l)

analog clock
apron
book jacket
bubble
coho
coral reef
guillotine
handkerchief
honeycomb
jellyfish
jigsaw puzzle
maze
mosquito net
nematode
paintbrush
pillow
poncho
quilt
rock python
safety pin
sea anemone
shower curtain
spider web
squirrel monkey
stingray
stole
sundial
tray
umbrella
wall clock
water snake
wreck

In [44]:
labels_df[labels_df.label == "wreck"]

,Unnamed: 0,image,label,percentage
119,119,existential_day_100/composites/composite_109.jpg,wreck,26.511700
186,186,existential_day_100/composites/composite_39.jpg,wreck,15.380889
189,189,existential_day_100/composites/composite_15.jpg,wreck,22.756485
200,200,existential_day_100/composites/composite_186.jpg,wreck,13.570417

In [47]:
labels_df.groupby("label").count().reset_index().sort_values(['image'], ascending=False)[["label", "image"]]

               label  image
6       handkerchief    529
13      mosquito net    290
18             quilt    280
24        spider web     80
9      jigsaw puzzle     49
7          honeycomb     43
23    shower curtain     42
17            pillow     41
1        book jacket     33
15        paintbrush     31
16         parachute     28
27          stingray     27
33        wall clock     26
31              tray     26
28             stole     20
14          nematode     19
35             wreck     16
12              maze     15
21         sea snake     14
32          umbrella      8
29           sundial      8
11  magnetic compass      7
5           envelope      7
34       water snake      5
30   swimming trunks      4
20       sea anemone      4
19   radio telescope      3
22        shower cap      3
2             bubble      3
3               coho      1
26   squirrel monkey      1
4         coral reef      1
25           spindle      1
8          jellyfish      1
10             junco      1
0       analog clock      1

In [46]:
labels_df = pd.read_csv("existential_day_103/composites/labels.csv")
labels_df["label"] = [x.split(",")[0] for x in labels_df["label"]]

for l in sorted(labels_df.label.unique()):
    print(l)

analog clock
book jacket
bubble
coho
coral reef
envelope
handkerchief
honeycomb
jellyfish
jigsaw puzzle
junco
magnetic compass
maze
mosquito net
nematode
paintbrush
parachute
pillow
quilt
radio telescope
sea anemone
sea snake
shower cap
shower curtain
spider web
spindle
squirrel monkey
stingray
stole
sundial
swimming trunks
tray
umbrella
wall clock
water snake
wreck

In [38]:
labels_df[labels_df.label == "wreck"]

,Unnamed: 0,image,label,percentage
25,25,existential_day_103/composites/composite_1350.jpg,wreck,13.731495
26,26,existential_day_103/composites/composite_981.jpg,wreck,13.731495
70,70,existential_day_103/composites/composite_837.jpg,wreck,13.731495
128,128,existential_day_103/composites/composite_1353.jpg,wreck,56.840439
341,341,existential_day_103/composites/composite_984.jpg,wreck,56.840439
427,427,existential_day_103/composites/composite_1125.jpg,wreck,13.731495
432,432,existential_day_103/composites/composite_909.jpg,wreck,13.731495
502,502,existential_day_103/composites/composite_840.jpg,wreck,56.840439
561,561,existential_day_103/composites/composite_1278.jpg,wreck,13.731495
583,583,existential_day_103/composites/composite_1053.jpg,wreck,13.731495
690,690,existential_day_103/composites/composite_1056.jpg,wreck,56.840439
766,766,existential_day_103/composites/composite_1281.jpg,wreck,56.840439
1061,1061,existential_day_103/composites/composite_912.jpg,wreck,56.840439
1239,1239,existential_day_103/composites/composite_1128.jpg,wreck,56.840439
1432,1432,existential_day_103/composites/composite_39.jpg,wreck,13.731495
1532,1532,existential_day_103/composites/composite_186.jpg,wreck,12.558079

In [39]:
labels_df.groupby("label").count().reset_index().sort_values(['image'], ascending=False)

               label  Unnamed: 0  image  percentage
6       handkerchief         529    529         529
13      mosquito net         290    290         290
18             quilt         280    280         280
24        spider web          80     80          80
9      jigsaw puzzle          49     49          49
7          honeycomb          43     43          43
23    shower curtain          42     42          42
17            pillow          41     41          41
1        book jacket          33     33          33
15        paintbrush          31     31          31
16         parachute          28     28          28
27          stingray          27     27          27
33        wall clock          26     26          26
31              tray          26     26          26
28             stole          20     20          20
14          nematode          19     19          19
35             wreck          16     16          16
12              maze          15     15          15
21         sea snake          14     14          14
32          umbrella           8      8           8
29           sundial           8      8           8
11  magnetic compass           7      7           7
5           envelope           7      7           7
34       water snake           5      5           5
30   swimming trunks           4      4           4
20       sea anemone           4      4           4
19   radio telescope           3      3           3
22        shower cap           3      3           3
2             bubble           3      3           3
3               coho           1      1           1
26   squirrel monkey           1      1           1
4         coral reef           1      1           1
25           spindle           1      1           1
8          jellyfish           1      1           1
10             junco           1      1           1
0       analog clock           1      1           1

In [35]:
labels_df = pd.read_csv("existential_day_103/cropped_inputs/labels.csv")
labels_df["label"] = [x.split(",")[0] for x in labels_df["label"]]

for l in sorted(labels_df.label.unique()):
    print(l)

brassiere
comic book
coral reef
handkerchief
honeycomb
jellyfish
lampshade
nematode
paintbrush
pillow
scuba diver
shower curtain
spider web
tray

In [36]:
labels_df.groupby("label").count().reset_index().sort_values(['image'], ascending=False)

             label  Unnamed: 0  image  percentage
3     handkerchief           7      7           7
5        jellyfish           3      3           3
12      spider web           3      3           3
2       coral reef           2      2           2
7         nematode           2      2           2
9           pillow           2      2           2
0        brassiere           1      1           1
1       comic book           1      1           1
4        honeycomb           1      1           1
6        lampshade           1      1           1
8       paintbrush           1      1           1
10     scuba diver           1      1           1
11  shower curtain           1      1           1
13            tray           1      1           1

In [48]:
labels_df = pd.read_csv("always_recycle_art/cropped_inputs/labels.csv")
labels_df["label"] = [x.split(",")[0] for x in labels_df["label"]]

for l in sorted(labels_df.label.unique()):
    print(l)

Band Aid
Christmas stocking
Windsor tie
backpack
balance beam
balloon
book jacket
car mirror
comic book
computer keyboard
conch
consomme
dial telephone
doormat
drumstick
electric fan
envelope
fire screen
fountain
goldfish
hammerhead
hand blower
handkerchief
harp
honeycomb
jack-o'-lantern
jellyfish
jigsaw puzzle
killer whale
king penguin
kite
loupe
manhole cover
matchstick
maze
megalith
mosquito net
mouse
nematode
orange
paddlewheel
parachute
pillow
ping-pong ball
plastic bag
platypus
poncho
prison
puck
quilt
radiator
radio telescope
rock beauty
rubber eraser
rule
sarong
slug
spider web
spotlight
stingray
stole
stove
strainer
switch
tennis ball
toilet tissue
toucan
tray
velvet
wall clock
wallet
water snake
window screen
wool
wreck

In [54]:
labels_df.sort_values("image")[["image", "label", "percentage"]] # .sort_values(['percentage'], ascending=False)  # different crops get different labels

,image,label,percentage
118,always_recycle_art/cropped_inputs/crop_0_v1.jpg,wool,17.275425
108,always_recycle_art/cropped_inputs/crop_0_v2.jpg,paddlewheel,16.022631
113,always_recycle_art/cropped_inputs/crop_0_v3.jpg,wool,21.735699
148,always_recycle_art/cropped_inputs/crop_10_v1.jpg,wall clock,21.273258
135,always_recycle_art/cropped_inputs/crop_10_v2.jpg,book jacket,39.636509
128,always_recycle_art/cropped_inputs/crop_10_v3.jpg,handkerchief,36.547806
39,always_recycle_art/cropped_inputs/crop_11_v1.jpg,envelope,33.600105
50,always_recycle_art/cropped_inputs/crop_11_v2.jpg,envelope,4.159215
63,always_recycle_art/cropped_inputs/crop_11_v3.jpg,doormat,8.628785
156,always_recycle_art/cropped_inputs/crop_12_v1.jpg,wallet,12.580687
168,always_recycle_art/cropped_inputs/crop_12_v2.jpg,poncho,53.344048
159,always_recycle_art/cropped_inputs/crop_12_v3.jpg,envelope,73.035278
81,always_recycle_art/cropped_inputs/crop_13_v1.jpg,maze,31.570169
71,always_recycle_art/cropped_inputs/crop_13_v2.jpg,maze,38.063210
74,always_recycle_art/cropped_inputs/crop_13_v3.jpg,maze,41.018589
119,always_recycle_art/cropped_inputs/crop_14_v1.jpg,jigsaw puzzle,57.657986
110,always_recycle_art/cropped_inputs/crop_14_v2.jpg,handkerchief,38.330097
111,always_recycle_art/cropped_inputs/crop_14_v3.jpg,handkerchief,44.591911
24,always_recycle_art/cropped_inputs/crop_15_v1.jpg,honeycomb,16.182236
37,always_recycle_art/cropped_inputs/crop_15_v2.jpg,velvet,40.099636
26,always_recycle_art/cropped_inputs/crop_15_v3.jpg,tray,33.386456
87,always_recycle_art/cropped_inputs/crop_16_v1.jpg,velvet,27.712158
93,always_recycle_art/cropped_inputs/crop_16_v2.jpg,velvet,15.423390
104,always_recycle_art/cropped_inputs/crop_16_v3.jpg,hammerhead,52.519901
16,always_recycle_art/cropped_inputs/crop_17_v1.jpg,kite,14.419577
7,always_recycle_art/cropped_inputs/crop_17_v2.jpg,dial telephone,15.480849
4,always_recycle_art/cropped_inputs/crop_17_v3.jpg,rule,34.810471
117,always_recycle_art/cropped_inputs/crop_18_v1.jpg,conch,28.205225
106,always_recycle_art/cropped_inputs/crop_18_v2.jpg,slug,30.280777
115,always_recycle_art/cropped_inputs/crop_18_v3.jpg,nematode,20.031096
...,...,...,...
121,always_recycle_art/cropped_inputs/crop_53_v1.jpg,tray,33.804428
114,always_recycle_art/cropped_inputs/crop_53_v2.jpg,jellyfish,7.069306
107,always_recycle_art/cropped_inputs/crop_53_v3.jpg,consomme,34.242378
84,always_recycle_art/cropped_inputs/crop_54_v1.jpg,computer keyboard,29.432386
76,always_recycle_art/cropped_inputs/crop_54_v2.jpg,jack-o'-lantern,6.838255
69,always_recycle_art/cropped_inputs/crop_54_v3.jpg,balance beam,33.599384
154,always_recycle_art/cropped_inputs/crop_55_v1.jpg,stingray,23.437153
163,always_recycle_art/cropped_inputs/crop_55_v2.jpg,Band Aid,15.059717
164,always_recycle_art/cropped_inputs/crop_55_v3.jpg,stingray,16.510586
44,always_recycle_art/cropped_inputs/crop_56_v1.jpg,spider web,57.666378
59,always_recycle_art/cropped_inputs/crop_56_v2.jpg,spider web,40.417904
54,always_recycle_art/cropped_inputs/crop_56_v3.jpg,spider web,40.363590
141,always_recycle_art/cropped_inputs/crop_57_v1.jpg,nematode,95.750717
124,always_recycle_art/cropped_inputs/crop_57_v2.jpg,matchstick,18.164150
139,always_recycle_art/cropped_inputs/crop_57_v3.jpg,nematode,53.262173
41,always_recycle_art/cropped_inputs/crop_5_v1.jpg,pillow,85.188736
53,always_recycle_art/cropped_inputs/crop_5_v2.jpg,velvet,14.295694
60,always_recycle_art/cropped_inputs/crop_5_v3.jpg,pillow,36.706455
155,always_recycle_art/cropped_inputs/crop_6_v1.jpg,envelope,43.136578
165,always_recycle_art/cropped_inputs/crop_6_v2.jpg,envelope,13.682024
162,always_recycle_art/cropped_inputs/crop_6_v3.jpg,handkerchief,39.481049
80,always_recycle_art/cropped_inputs/crop_7_v1.jpg,envelope,60.144943
68,always_recycle_art/cropped_inputs/crop_7_v2.jpg,envelope,64.731247
77,always_recycle_art/cropped_inputs/crop_7_v3.jpg,book jacket,67.546387
147,always_recycle_art/cropped_inputs/crop_8_v1.jpg,tray,40.648148
132,always_recycle_art/cropped_inputs/crop_8_v2.jpg,book jacket,20.730835
131,always_recycle_art/cropped_inputs/crop_8_v3.jpg,tray,57.500965
40,always_recycle_art/cropped_inputs/crop_9_v1.jpg,prison,6.745750
52,always_recycle_art/cropped_inputs/crop_9_v2.jpg,doormat,22.867229
61,always_recycle_art/cropped_inputs/crop_9_v3.jpg,puck,7.528018

In [22]:
labels_df[labels_df.label == "wreck"]

,Unnamed: 0,image,label,percentage
72,72,always_recycle_art/cropped_inputs/crop_46_v3.jpg,wreck,62.718616

In [34]:
labels_df.groupby("label").count().reset_index().sort_values(['image'], ascending=False)

                 label  Unnamed: 0  image  percentage
16            envelope          15     15          15
22        handkerchief          13     13          13
68              velvet          12     12          12
6          book jacket          10     10          10
67                tray          10     10          10
57          spider web           6      6           6
27       jigsaw puzzle           5      5           5
19            goldfish           5      5           5
43      ping-pong ball           4      4           4
38            nematode           4      4           4
34                maze           4      4           4
5              balloon           3      3           3
28        killer whale           3      3           3
25     jack-o'-lantern           3      3           3
13             doormat           3      3           3
73                wool           3      3           3
42              pillow           3      3           3
53       rubber eraser           2      2           2
59            stingray           2      2           2
24           honeycomb           2      2           2
62            strainer           2      2           2
20          hammerhead           2      2           2
3             backpack           2      2           2
48                puck           2      2           2
52         rock beauty           1      1           1
54                rule           1      1           1
56                slug           1      1           1
50            radiator           1      1           1
49               quilt           1      1           1
55              sarong           1      1           1
..                 ...         ...    ...         ...
37               mouse           1      1           1
45            platypus           1      1           1
21         hand blower           1      1           1
2          Windsor tie           1      1           1
4         balance beam           1      1           1
7           car mirror           1      1           1
8           comic book           1      1           1
9    computer keyboard           1      1           1
10               conch           1      1           1
11            consomme           1      1           1
12      dial telephone           1      1           1
14           drumstick           1      1           1
15        electric fan           1      1           1
17         fire screen           1      1           1
18            fountain           1      1           1
23                harp           1      1           1
44         plastic bag           1      1           1
26           jellyfish           1      1           1
29        king penguin           1      1           1
30                kite           1      1           1
31               loupe           1      1           1
32       manhole cover           1      1           1
33          matchstick           1      1           1
35            megalith           1      1           1
36        mosquito net           1      1           1
1   Christmas stocking           1      1           1
39              orange           1      1           1
40         paddlewheel           1      1           1
41           parachute           1      1           1
74               wreck           1      1           1

[75 rows x 4 columns]